openapi: 3.0.0
info:
  title: exo2
  description: Api to test manipulation about parameters and responses
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /users:
    get:
      summary: Get a user in the list
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: The number page to retrieve
        - in: query
          name: size
          schema:
            type: integer
            default: 20
            minimum: 1
          description: Number of user per page
      responses:
        "200":
          description: List of user found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                    format: email
                required:
                  - id
                  - name
                  - email
        "400":
          description: Bad types for provided query parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
              example:
                error: "Bad types for provided query parameters"
