openapi: 3.0.0
info:
  title: exo3
  description: Api test about managing task
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - description: Local development server
paths:
  /tasks:
    get:
      summary: Get list of all task
      operationId: GetTasks
      responses:
        "200":
          description: Return the list of all task with status 200
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    post:
      summary: Create a list of task
      operationId: createTasks
      requestBody:
        description: List of task to create
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Task"
            example:
              - id: 2
                title: Learn OpenAPI
                completed: false
              - id: 3
                title: Buy a bread
                completed: false
      responses:
        "201":
          description: List of task is created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    delete:
      summary: Delete a list of tasks by IDs
      operationId: deleteTasks
      requestBody:
        description: List of task IDs to delete
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              example: [1, 3]
      responses:
        "200":
          description: List of deleted tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Faire les courses
        completed:
          type: boolean
          example: false
