openapi: 3.0.0
info:
  title: exo4
  description: Searching product
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /products:
    get:
      summary: Search for products
      operationId: searchProducts
      parameters:
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/q"
      responses:
        "200":
          description: List of the products matching the search criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                multipleProducts:
                  summary: Multiple products found
                  value:
                    - name: white chocolate
                      expiration_datetime: 2025-12-31T23:59:00Z
                      price: 4.99
                    - name: Orange juice
                      expiration_datetime: 2024-06-30T12:00:00Z
                      price: 2.5
                emptyList:
                  summary: No products found
                  value: []
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: a black chocolate
        expiration_datetime:
          type: string
          format: date-time
          example: 2025-12-31T23:59:00Z
        price:
          type: number
          format: float
          example: 4.99
      required:
        - name
        - expiration_datetime
        - price
  parameters:
    limit:
      name: limit
      in: query
      description: Max of number to return
      required: false
      schema:
        type: integer
        example: 10
    q:
      name: q
      in: query
      description: term search
      required: false
      schema:
        type: string
        example: chocolate
