openapi: 3.0.0
info:
  title: exo5
  description: Api with authentification + tags
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: localhost development
paths:
  /products:
    get:
      tags:
        - Products
  /orders:
    get:
      tags:
        - Orders
      summary: Get paginated list of orders
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/size"
      responses:
        "200":
          description: Paginated list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
              examples:
                example1:
                  summary: Two orders
                  value:
                    - identifier: 101
                      customer_name: John Doe
                      creation_datetime: 2025-09-01T10:30:00Z
                      total_amount: 150.75
                    - identifier: 102
                      customer_name: Alice Smith
                      creation_datetime: 2025-09-01T12:00:00Z
                      total_amount: 89.99
    post:
      tags:
        - Orders
      summary: Create a new order
      security:
        - basicAuth: []
      requestBody:
        description: Order to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
            example:
              identifier: 103
              customer_name: Bob Marley
              creation_datetime: 2025-09-01T15:00:00Z
              total_amount: 200.00
      responses:
        "201":
          description: Order successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: Basic
  parameters:
    page:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        example: 1
    size:
      name: size
      in: query
      description: Number of items per page
      required: false
      schema:
        type: integer
        example: 10
  schemas:
    Order:
      type: object
      properties:
        identifier:
          type: integer
          example: 101
        customer_name:
          type: string
          example: John Doe
        creation_datetime:
          type: string
          format: date-time
          example: 2025-09-01T10:30:00Z
        total_amount:
          type: number
          format: float
          example: 150.75
      required:
        - identifier
        - customer_name
        - creation_datetime
        - total_amount
