openapi: 3.0.0
info:
  title: exo6
  description: Best practice for OSA
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: localhost development
paths:
components:
  schemas:
    UserProfile:
      type: object
      properties:
        identifier:
          type: string
        personalInfo:
          $ref: "#/components/schemas/PersonalInfo"
        address:
          $ref: "#/components/schemas/Address"
        preferences:
          $ref: "#/components/schemas/Preferences"
      required:
        - identifier
        - personalInfo
        - address
        - preferences
    CreateUserProfile:
      type: object
      properties:
        personalInfo:
          $ref: "#/components/schemas/PersonalInfo"
        address:
          $ref: "#/components/schemas/Address"
        preferences:
          $ref: "#/components/schemas/Preferences"
      required:
        - personalInfo
        - address
        - preferences

    PersonalInfo:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        birthdate:
          type: string
          format: date
        email:
          type: string
          format: email
      required:
        - first_name
        - last_name
        - email

    Address:
      type: object
      properties:
        address_street:
          type: string
        address_city:
          type: string
        address_country:
          type: string
        address_postal_code:
          type: integer
      required:
        - address_street
        - address_city
        - address_country
        - address_postal_code

    Preferences:
      type: object
      properties:
        needs_newsletter:
          type: boolean
        language:
          type: string
          enum: [mg, fr, eng]
      required:
        - needs_newsletter
        - language
